cruise-automation/webviz

docs/package-lock.json
docs/package.json
packages/regl-worldview/package.json

- Add npm files field to keep node_modules clean
- Test regl-worldview 0.0.1 by adding to docs dependency

Add npm files and install regl-worldview as docs dependency

---

.circleci/config.yml

Would like to integrate flowtype checking into the CI pipeline.  Some of the whitespace changes are vscode autoformatting the yaml.
Test plan: circle should pass.

Add flow to circle-ci

---

docs/src/App.js
package.json

Classic `HashRouter` issue, with a simple workaround.
Test plan: tested manually.

Scroll to top when navigating in the docs

---

docs/src/Demo.js

Nicer and faster demo on landing page

---

package-lock.json
package.json
webpack.config.js

Per example at https://github.com/mdx-js/mdx/blob/ad58be384c07672dc415b3d9d9f45dcebbfd2eb8/docs/advanced/retext-plugins.md

docs: use retext-smartypants

---

docs/src/Demo.js
docs/src/Docs.js
docs/src/Landing.js
docs/src/jsx/CameraStateControls.js
docs/src/jsx/CodeEditor.js
docs/src/jsx/Hitmap.js
docs/src/jsx/InputNumber.js
docs/src/jsx/Overlay.js
docs/src/theme.js
docs/src/utils/Scrubber.js
docs/src/utils/Slider.js
docs/src/utils/Switch.js

- Add theme config for colors, fonts and spacing. The settings are mostly based on our internal styleguide, with minor adjustments. 
- Update existing components to use the theme config 
Note: more design updates from Eden/Jeff will come later.

Add theme config to globally control colors, fonts and spacing

---

packages/@cruise-automation/button/package.json
packages/@cruise-automation/tooltip/package.json
packages/react-key-listener/package.json
packages/regl-worldview/package.json
packages/webviz-core/package.json

So we get links back to Github from npm on the next release.

Add repository field to package.jsons

---

docs/src/2.1.QuickStart.mdx
docs/src/3.5.BrowserSupport.mdx
docs/src/routes.js
packages/regl-worldview/README.md

- Add a simple browser support sections to docs 
- Update umd link which will automatically redirect to the latest minified regl-worldview umd build

Add browser support to docs and update umd link

---

docs/src/Demo.js
docs/src/Docs.js
docs/src/Landing.js
docs/src/styles/App.css

- Use underline for link styles
- Adjust heading line height
- Adjust sphere size in demo

Style nits

---

docs/src/jsx/Overlay.js
docs/src/jsx/utils/WorldviewCodeEditor.js

Current: https://codesandbox.io/s/4z889qrzw7 
Fixed: https://codesandbox.io/s/p3p5v4567x

Fix Overlay disappearing in CodeSandbox

---

.circleci/config.yml

Which uses Chrome 72 instead of 71.

Use cruise/webviz-ci:0.0.3 in CI

---

packages/regl-worldview/src/commands/Lines.js
packages/regl-worldview/src/stories/lines.stories.js

I made the story a bit more fun.

 1️⃣📈 Prevent an off by 1 error for lines without points

---

packages/webviz-core/README.md
packages/webviz-core/src/components/MessageHistory/FrameCompatibility.js
packages/webviz-core/src/components/MessageHistory/MessageHistoryOnlyTopics.js
packages/webviz-core/src/components/MessageHistory/index.js
packages/webviz-core/src/components/MessageHistory/topicPathSyntax.help.md
packages/webviz-core/src/components/Select/Option.js
packages/webviz-core/src/components/Select/Option.module.scss
packages/webviz-core/src/components/Select/Select.js
packages/webviz-core/src/components/Select/Select.module.scss
packages/webviz-core/src/components/Select/index.js
packages/webviz-core/src/panels/Plot/index.help.md
packages/webviz-core/src/panels/Rosout/index.help.md
packages/webviz-core/src/panels/Rosout/index.stories.js
packages/webviz-core/src/panels/diagnostics/DiagnosticSummary.help.md
packages/webviz-core/src/types/Messages.js

Changelog:
- Fix multiple encoding error from ImageView panel
- Add Select and Option components

Update packages/webviz-core from internal repo

---

.circleci/config.yml
Dockerfile

I already published this as cruise/webviz-ci:0.0.6.

Update to latest LTS Node.js and Chrome 73 in Dockerfile

---

docs/src/2.1.QuickStart.mdx
docs/src/2.2.Introduction.mdx
docs/src/2.3.RenderingObjects.mdx
docs/src/2.4.ManagingCamera.mdx
docs/src/2.4.ManagingTheCamera.mdx
docs/src/2.5.AddingInteractivity.mdx
docs/src/3.4.MouseEvents.mdx
docs/src/Docs.js
docs/src/jsx/utils/CodeSandboxEmbed.js
docs/src/routes.js

Add quickstart tutorial for worldview. Probably easier to review/modify locally.
Outline: 
- Introduction
- Rendering Objects
- Managing the Camera
- Adding Interactivity

Add a quickstart tutorial

---

.flowconfig

Removing dead code from `.flowconfig`
All existing tests and checks should still pass
Does not impact versioning.

Get rid of dead code in .flowconfig

---

packages/regl-worldview/src/utils/commandUtils.js

Introduced a breaking change in my previous [PR](https://github.com/cruise-automation/webviz/pull/124/files#diff-6c2f2c5a71141e8b99e1539e04b5dd6eR87). This PR fixes it.

Continue to export blend to avoid breaking change

---

README.md
docs/public/index.html

More readme updates

---

package.json

We seem to hit the timeout in like 20% of the builds or so.

Bump screenshot timeout

---

packages/regl-worldview/src/commands/index.js

Missed this export in my previous PR #166 
Manually tested with internal repo and it works.
Patch.

Fix PolygonBuilder export

---

docs/src/2.5.AddingInteractivity.mdx
docs/src/3.4.MouseEvents.mdx
docs/src/jsx/api/MouseEvents.js
docs/src/jsx/api/MouseEventsInstanced.js
docs/src/jsx/commands/FilledPolygonsHitmap.js
docs/src/jsx/commands/GLTFSceneHitmap.js
docs/src/jsx/commands/LinesHitmap.js
docs/src/jsx/examples/Hitmap.js
docs/src/jsx/tutorials/AddRemoveObstacles.js
docs/src/jsx/tutorials/StopReleaseDuck.js
packages/regl-worldview/src/Worldview.js
packages/regl-worldview/src/WorldviewContext.js
packages/regl-worldview/src/commands/Command.js
packages/regl-worldview/src/commands/DrawPolygon/index.js
packages/regl-worldview/src/commands/GLTFScene.js
packages/regl-worldview/src/types/index.js
packages/regl-worldview/src/utils/HitmapIdManager.js
packages/regl-worldview/src/utils/getHitmapDefaults.js
packages/regl-worldview/src/utils/getHitmapDefaults.test.js

_What's the motivation for this change, what approach did you take, and why?_
_How was this change tested & verified?_
_Does this change necessitate a [major, minor, or patch](https://semver.org/) semver update for the affected package?_

Add stacked object rendering

---

jest/jest.config.js
package-lock.json
package.json
packages/webviz-core/package-lock.json
packages/webviz-core/package.json
packages/webviz-core/src/test/stubs/MonacoEditor.js
webpack.config.js

- Add dependencies necessary for development of future Node Playground panel

Add dependencies necessary for future Node Playground panel

---

package-lock.json
packages/regl-worldview/package-lock.json

The package-lock files were out of date with the package.json.
Update them to keep them in sync.
Tests are not necessary
None

Fix minor package-lock issues

---

docs/public/dist/wasm-lz4.wasm

Missed this file in #188.
Was able to run `npm run docs-deploy` successfully. 
No change.

Delete wasm-lz4.wasm file

---

docs/src/2.1.QuickStart.mdx
docs/src/3.4.MouseEvents.mdx
docs/src/5.1.MigratingToVersion0.2.x.mdx
docs/src/routes.js

Add a new doc for migrating worldview from 0.1.x to 0.2.x.
Manually ran docs
None

Add docs for migrating from 0.1.x to 0.2.x

---

packages/regl-worldview/src/commands/GLTFScene.js

Fix GLTFScene regression causing bug report. We unnecessarily
checked for an attribute that wasn't needed for rendering.
Manually checked that GLTFScene works with a file that previously failed.
This will require a minor version bump.

Fix GLTF regression

---

package-lock.json
package.json

We are adding this dependency in the closed repo so that we can use
it in open source soon. Add it here too.
Test plan: none

Add dependency for later changes

---

jest/jest.config.js

A more generic mock for the UserNodePlayer workers (now expanded to two).
It will pass CI in our private version.
None.

Tweak UserNodePlayer workers mock

---

jest/jest.config.js

Reverts #214.
It'll start passing private CI.
None

Revert "Tweak mock (#214)"

---

jest/jest.config.js

Reverts cruise-automation/webviz#218.
This will cause some issues with CI until I can merge in changes from our private repo--should (hopefully) be only 30 mins or so.

Tweak worker mock

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json
packages/regl-worldview/src/commands/Command.js
packages/regl-worldview/src/stories/assertionStories/Worldview.stories.js
packages/webviz-core/package-lock.json

Fix bug of switching event and ray in object callbacks. Fixes #226.
Included integration test.
Upgraded to version 0.2.3.

Fix mouse event argument mix-up

---

docs/src/4.6.Lines.mdx
docs/src/jsx/allDemos.stories.js
docs/src/jsx/allLiveEditors.js
docs/src/jsx/commands/LinesPoses.js
packages/regl-worldview/src/commands/Lines.js
packages/regl-worldview/src/types/index.js

Make the lines component able to take multiple poses per marker.
This will help us implement some markers that have different poses
instead of different points. While we're at it, make the loading
of colors into lines more efficient by passing a typed array
directly to regl.
Test plan: added a story, test that existing tests continue working.
Versioning impact: this will require a minor version bump

Make lines truly instanced

---

.flowconfig

enable optional chaining in Flow

---

docs/src/3.4.MouseEvents.mdx

These docs were incorrect: they were based on an earlier version of
the hitmap code. Update them to correct the hitmap usage.
No test needed, no versioning impact.

Update worldview hitmap docs

---

docs/src/jsx/allLiveEditors.js
docs/src/jsx/commands/GLText.js
package-lock.json
packages/regl-worldview/package.json

Minor cleanup — following up on @vidaaudrey's feedback from #291

GLText cleanup & review feedback

---

README.md
docs/public/index.html
docs/public/worldview/index.html

Add info about connecting to rosbridge_server

---

README.md

To communicate better our direction with the app.

Note about customizing Webviz #304

---

package-lock.json
packages/regl-worldview/src/Worldview.js
packages/regl-worldview/src/WorldviewContext.js
packages/regl-worldview/src/commands/Arrows.js
packages/regl-worldview/src/commands/Axes.js
packages/regl-worldview/src/commands/Command.js
packages/regl-worldview/src/commands/DrawPolygon/index.js
packages/regl-worldview/src/commands/FilledPolygons.js
packages/regl-worldview/src/commands/GLText.js
packages/regl-worldview/src/commands/Grid.js
packages/regl-worldview/src/stories/worldviewAssertionUtils.js
packages/regl-worldview/src/types/index.js
packages/regl-worldview/src/utils/HitmapObjectIdManager.js
packages/webviz-core/package-lock.json
packages/webviz-core/src/panels/ThreeDimensionalViz/commands/LaserScans.js
packages/webviz-core/src/panels/ThreeDimensionalViz/commands/LinedConvexHulls.js

This flow type was missing for a while, causing a bunch of flow
errors to pile up. Remove so that we can have Command fully typed.
Test plan: existing stories and functional integration tests should
be enough
Versioning impact: This can go out with the next version release

Add flow typing to Worldview Command

---

.circleci/config.yml
package-lock.json
package.json

Ran into an issue where tests started failing in my internal PR because
this version was out of date. Updating this seems to pass all the tests
still, and should unblock my internal PR.

Update enzyme-adapter-react-16 to latest version

---

jest/jest.config.js

Add this line, which is required to get internal CI to pass so that
we can add this worker to the open-source version.

Update jest config

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json

Update the version number for regl-worldview 
No need to test it
Minor version update

Update worldview version

---

package.json

Remove the debug output from this job - it might speed back up the
build.

Remove --debug from screenshot job

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json

Update minor version prior to next release, including several fixes for GLText and enabling selection for that command.
Minor

Bump minor version number

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json

This release includes fixes for several issues with `<GLText />` command.

Release v0.6.1

---

.circleci/config.yml

Remove `-v /root:/root` from `docker run`

---

packages/@cruise-automation/button/src/index.js
packages/@cruise-automation/button/src/index.test.js

So users can use the onFocus callback.
Test plan: Added a test

Pass through onFocus prop to <button>

---

webpack.config.js

We have an incoming monaco-editor package bump that requires a new loader for `*.ttf` extensions. In order to pass CI for our private repo, this loader handler needed to be added. 
Should pass CI.
None!

Update file-loader for ttf files

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json

New Worldview release 
All existing tests and stories must pass
New minor version

Worldview Release v0.7.0

---

.flowconfig
jest/jest.config.js
jest/rawTransform.js
webpack.config.js

There will be a subsequent change in Node Playground that will allow `*.ts` files, which will be stringified for Node Playground to process. This PR gets ahead of the tooling change to make this possible so our CI can pass.

Update config in preparation for Node Playground Changes

---

.flowconfig

I incorrectly copied the path for the flowconfig in #420.
None.

Fix flowconfig path

---

jest/jest.config.js

Another one-liner -- forgot to put the `*.ts` transform under `transform` 🤦  
Will be tested in the private repo.
None.

Fix jest transform

---

packages/regl-worldview/src/commands/GLText.js

This error occurs when a texture is beyond the max texture size. It
only shows up on certain linux machines right now, and started in
the past month. It's possible that this error is because of some
error in the messages we're seeing, but a more likely reason is the
launch of the gltext feature.
We are creating an atlas in GLText with a limited width, which means
that the height direction grows much larger than the width. It's
possible (not reproduced) that this causes the height to exceed
GL_MAX_TEXTURE_SIZE on some machines. Instead set the width of the
atlas to the actual GL_MAX_TEXTURE_SIZE, so that we give our
characters more horizontal space and hope that we don't exceed the
height limits.
Test plan: hope

Attempt to fix "invalid height" regl errors

---

packages/regl-worldview/package.json
packages/webviz-core/package-lock.json

Bump worldview version to 0.7.2

---

jest/jest.config.js
webpack.config.js

I needed to tweak the regex slightly between Jest/Webpack to allow for Node Playground template files. 
Should pass internal CI.
None.

Update webpack/jest matching for *.ts files

---

packages/react-key-listener/package-lock.json
packages/regl-worldview/package-lock.json
packages/webviz-core/package-lock.json

(Based on #454 to make CI pass; thanks @rk-yen!)
When doing a `npm run bootstrap` the files added to the PR got changed. To keep the repository up-to-date, we should commit the updates to the lock files.
After committing the change, `npm run bootstrap` was run again. And, it was verified that no files were in the `modified` state.
This change has no impact on versioning.

Updates to various package-lock.json

---

.github/pull_request_template.md
HISTORY.md
README.md

Update docs with Slack instructions

---

packages/webviz-core/package-lock.json
packages/webviz-core/package.json

Mirrors #467. @janpaul123 [foretold](https://github.com/cruise-automation/webviz/pull/467#pullrequestreview-432795653) what would occur if I forgot to update the private repo:
> Be sure to also make an internal PR for the changes in packages/webviz-core, otherwise these will get reverted at the next release.
Tested manually.
None.

Remove monaco dependencies from webviz package

---

README.md

Add a gif to the readme

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json

Update version number before publishing

Bump version number

---

Dockerfile-static-webviz
Dockerfile-webviz-ci

I am installing a dependency that needs a newer version of node -
lets bump it.

Bump node version

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json

Worldview v0.10.0

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json

Worldview v0.11.0

---

packages/webviz-core/src/panels/ThreeDimensionalViz/LaserScanVert.js
packages/webviz-core/src/panels/ThreeDimensionalViz/TopicSettingsEditor/LaserScanSettingsEditor.js
packages/webviz-core/src/panels/ThreeDimensionalViz/TopicSettingsEditor/MarkerSettingsEditor.js
packages/webviz-core/src/panels/ThreeDimensionalViz/commands/LaserScans.js

Support changing the color of laserscans (copy)

---

packages/regl-worldview/src/commands/Points.js
packages/regl-worldview/src/stories/Points.stories.js

Fix marker array scaling with small scale (copy)

---

packages/regl-worldview/package.json

Releasing Worldview to include changes in #530.

Release Worldview @0.12.2

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json

New release for Worldview, including fixes for custom render states

Worldview Release v0.13.0

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json

Worldview v0.13.1 Release

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json

New Worldview version to fix performance issues

Bump Worldview version

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json

Worldview Release v0.13.3

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json

Messed up the npm publish, trying again.

Bump regl-worldview version

---

.dockerignore
.gitignore
Dockerfile-static-webviz
README.md
package.json

Copying #542 to bypass the CI credential problem (We'll move the screenshots from AWS to GCP soon.).

Optimize Dockerfile for smaller container images (copy) 

---

jest/jest.config.js

Test plan: Only affects tests.

Use UserNodePlayer worker mock

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json
packages/regl-worldview/src/WorldviewContext.js

Fix bug with regl-worldview context attributes, which were not being
passed to children.

Fix bug with regl-worldview context attributes

---

packages/regl-worldview/package.json
packages/regl-worldview/src/WorldviewContext.js
packages/webviz-core/package-lock.json
packages/webviz-core/package.json

Copy of #614 with minor fix on build error (missing package).

Worldview: Paint again if onDirty was called during paint (copy of #614)

---

README.md

Update README to add section on Foxglove.

Update README to mention Foxglove

---

package-lock.json

Changing package-lock.json links from internal `artifactory.robot.car` to public `registry.npmjs.org`. Not sure why it is working fine CI, but fixing is good regardless. 
- Green CI is sufficient

Fix artifacts links in package-lock.json

---

.circleci/config.yml
Dockerfile-webviz-ci

Install rust build tools in docker
