cruise-automation/webviz

packages/regl-worldview/rollup.config.js
packages/regl-worldview/src/commands/Cones.js
packages/regl-worldview/src/commands/Cubes.js
packages/regl-worldview/src/commands/Cylinders.js
packages/regl-worldview/src/commands/Spheres.js
packages/regl-worldview/src/commands/Triangles.js
packages/regl-worldview/src/commands/index.js

- Export regl commands for reusability 
- Build a separate type file so we could use `import type { Vec3, Arrow } from 'regl-worldview/dist/types'`

Export commands and build types

---

.circleci/config.yml
packages/regl-worldview/babel.config.js
packages/regl-worldview/rollup.config.js

I broke this earlier when updating babel.config.js. Looks like this
fixes it. I wonder if we can further simplify the rollup config, but
for now I’m going to leave it at this.
Test plan: added build step to Circle CI.

Fix the building of regl-worldview

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json
packages/regl-worldview/rollup.config.js
packages/regl-worldview/src/commands/Text.js
packages/regl-worldview/src/stories/Container.js
packages/regl-worldview/src/stories/FloatingBox.js
packages/regl-worldview/src/stories/hitmap.js

We only had a few minor dependencies on it, but it caused a bunch of
problems, ranging from hacks in the Rollup config, to having to keep
the version in sync with the version in the root of the repo (for docs).
So I figured I’d just remove it.
Test plan: verified manually that stories and docs work properly now.
The rest is somewhat covered by CI.

Remove styled-components dependency from regl-worldview

---

docs/public/index.html
docs/src/App.js
package-lock.json
package.json
webpack.config.js

Using a HashRouter instead of BrowserRouter, otherwise we’d have to
somehow deal with 404s (using something like
https://github.com/rafrex/spa-github-pages or so, but that seems pretty
hacky).
Test plan: it works: https://cruise-automation.github.io/webviz

Make docs deployable to Github Pages

---

lerna.json
package-lock.json
package.json
packages/regl-worldview/package.json
packages/regl-worldview/rollup.config.js

Generate sourcemaps for all build files and uglify umd build. 
Ref: https://developers.google.com/web/tools/chrome-devtools/javascript/source-maps

Generate sourcemaps for all builds

---

package-lock.json
package.json
webpack.config.js

The code highlighting for markdown code blocks is lost when navigating to a different page. Fixed by adding rehypePrism plugin (Ref: https://github.com/mdx-js/mdx/issues/253). 
Before:
After:

Fix code highlighting when navigating to different pages

---

docs/src/jsx/CodeEditor.js

Overlay it on top of the output so you can actually see it when on a
small screen.
Test plan: manual.

Better positioning of error message

---

docs/src/3.1.Worldview.mdx
docs/src/3.10.Lines.mdx
docs/src/3.11.Overlay.mdx
docs/src/3.12.Points.mdx
docs/src/3.13.Spheres.mdx
docs/src/3.14.Text.mdx
docs/src/3.15.Triangles.mdx
docs/src/3.2.Camera.mdx
docs/src/3.3.Command.mdx
docs/src/3.4.Arrows.mdx
docs/src/3.5.Cones.mdx
docs/src/3.6.Cubes.mdx
docs/src/3.7.Cylinders.mdx
docs/src/3.8.FilledPolygons.mdx
docs/src/jsx/CodeEditor.js
docs/src/jsx/allLiveEditors.js
docs/src/utils/icons/Done.js
packages/regl-worldview/src/Worldview.js
packages/regl-worldview/src/commands/Command.js

- Add `optional` column to some props tables
- Use code style for names and defaults in props tables
- Minor left-over work from prev PR #49. Somehow I forgot to push up yesterday

Docs: add optional column and use code style for names and defaults

---

package.json

This runs significantly faster.
Test plan: did a manual deploy with NODE_ENV=production and things are
indeed much faster. Will verify again after merging.

Deploy docs using NODE_ENV=production

---

packages/regl-worldview/src/WorldviewContext.js

Enable the use of Uint32Array for element index arrays.
Probably we should add a hook to allow customizing the set of extensions, but it doesn't seem like a big deal to just add one more and I doubt we'll need to add them very often :)

add oes_element_index_uint extension

---

packages/regl-worldview/src/commands/Command.js
packages/regl-worldview/src/commands/Command.test.js
packages/regl-worldview/src/index.js

Also export WorldviewReactContext so non-command components can grab access to the regl instance.

Allow custom getHitmapProps() function to be passed to simple commands.

---

packages/regl-worldview/src/camera/CameraStore.js

Problem: currently we  consolidate `cameraState` updates in `_setStateAndNotify ` and skip updating `cameraState` if the next state is deeply equal to the current state. This approach has two issues:
- potential race condition as `cameraState` can be set elsewhere during the movement (e.g. worldview props)
- not efficient because we only need to compare a few primitives before updating the `cameraState`: `x`, `y`, `distance`. 
Test plan: test the new esm build internally, we should be able to rotate the 3d view when the webviz bag play is paused. 
Note: upon further investigation, we found the root problem is related to object spread in Chrome. Changing `const newState = {...this.state, thetaOffset: newThetaOffset}` to `const newState = Object.assign({}, this.state); newState.thetaOffset …

Fix inconsistent updates in camera rotation

---

packages/regl-worldview/src/stories/Cubes.stories.js

We added support for passing a `getHitmapProps` callback function into simple commands in addition to the old support for `getHitmapId` - this adds an interactive storybook to ensure the behavior works.
Test plan: is a manual test.

Add story for dynamic hitmap.

---

docs/src/4.12.GLTFScene.mdx
packages/regl-worldview/src/commands/GLTFScene.js
packages/regl-worldview/src/utils/parseGLB.js

- Add support for [`baseColorFactor`](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#pbrmetallicroughness).
- Make `baseColorTexture` optional (it's assumed to be white by default).
- Add a prop to set `alpha` globally, since the baseColor stuff comes from the model itself which isn't expected to change dynamically.
- Enable `blend` to allow alpha values to take effect.
- Fix an issue where `bitmap.close()` was called multiple times if the same image texture was used for multiple samplers, and fix some issues with models that don't have any images.
- Fix calculation of `length` for typed arrays when the accessor is offset from the start of the bufferView.

GLTFScene: baseColorFactor & bug fixes

---

.eslintrc.js
package-lock.json
package.json
webpack.config.js

- Add eslint plugin for react hooks as it'll be used in webviz-core 
- Use webpack `file-loader` to load `.bag` files (this will be used for loading ROS bag file in storybook)

Update eslint and support reading .bag files

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json

We use @babel/transform-runtime in the [rollup config](https://github.com/cruise-automation/webviz/blob/master/packages/regl-worldview/rollup.config.js#L22) to reduce the codesize. As specified in the doc [here](https://babeljs.io/docs/en/babel-plugin-transform-runtime), we need to add @babel/runtime as prod dependency. 
Test: 
CodeSandBox only works if this dependency is present. https://codesandbox.io/s/j322yv070v 
Will publish a new package version to test once the PR is merged.

Add @babel/runtime as prod dependency

---

packages/regl-worldview/src/Worldview.js
packages/regl-worldview/src/WorldviewContext.js
packages/regl-worldview/src/commands/Command.js
packages/regl-worldview/src/utils/common.js

The current umd build doesn't work without `const process = {}`  https://codepen.io/vidaaudrey/pen/WPwmqg  
Fix by always checking for `process` and `process.env` before getting NODE_ENV.

Fix process undefined in umd build

---

packages/regl-worldview/src/Worldview.js
packages/regl-worldview/src/WorldviewContext.js
packages/regl-worldview/src/commands/Command.js
packages/regl-worldview/src/stories/Cubes.stories.js
packages/regl-worldview/src/stories/PerComponentHitmapStory.js
packages/regl-worldview/src/types/index.js

This PR adds component-based mouse interactions so that consumers can add `onClick` or `onMouseMove` etc. to a command component.
The story added showcases 3 interactions, clicking for details, double clicking for removal, and hovering for changing the mouse cursor.
This takes a similar approach from a previous PR, without a lot of the extra overhead.

Component-based mouse interactions

---

docs/src/Demo.js

So that there isn’t any scrolling in the editor there, which is
annoying, especially on mobile devices.
Test plan: verified manually.

Increase the editor height on the Worldview homepage a bit

---

.eslintrc.js
packages/regl-worldview/src/WorldviewContext.js

We get thousands of these `hitmap draw skipped, props was falsy` log statements as this fires constantly and they're more or less useless without any info.  I think by default this should be set to `debug` or this log should be removed completely as falsy hitmap draw props don't cause issues.

Shift log to debug, add more info

---

packages/regl-worldview/src/WorldviewContext.js

encountered a bug where calling `raycast` from [react-dnd](https://github.com/react-dnd/react-dnd) had `this` as undefined.
wonder if it's a good idea to bind this to all of these class functions or if we're comfortable with just doing it for `raycast` for now.

Bind raycast

---

docs/src/Demo.js

The CodeSandbox link on the landing page was broken. Fixed by adding the right props.
Before: https://codesandbox.io/s/140519qkjl 
Fixed: https://codesandbox.io/s/yj2308xr5z

Fix CodeSandbox link for landing page

---

docs/src/4.5.FilledPolygons.mdx
docs/src/jsx/FilledPolygons.js
packages/regl-worldview/src/commands/FilledPolygons.js
packages/regl-worldview/src/types/index.js

This continues @troygibb's work from https://github.com/cruise-automation/webviz/pull/91. 
After some discussion we realized that the FilledPolygon component should be able to support both formats for both color and points, the former of which already works.

Amend FilledPolygon types

---

.vscode/settings.json
docs/src/3.1.Worldview.mdx
docs/src/jsx/Hitmap.js
docs/src/jsx/Overlay.js
packages/regl-worldview/src/Worldview.js
packages/regl-worldview/src/commands/GLTFScene.js

The Overlay sometimes go over the Worldview main container which is not the expected behavior: [Codesandbox](https://codesandbox.io/s/nwzr8o3wll?fontsize=14)
The main cause is that we are using `React.Fragment` as the root container for Worldview, and it doesn't have any styling. When the Overlay gets rendered, it'll be at the same level as Worldview. 
Use `div` instead of `React.Fragment` for Worldview root container and add default `relative` positioning so the Overlay will be positioned correctly relative it's parent. I also add `style` prop to allow consumer to add more custom styling to the root container. 
Manually test the Hitmap and Overlay examples to make sure the content doesn't overflow the container.

Fix Overlay so it doesn't flow outside of Worldview by default 

---

packages/regl-worldview/src/commands/Command.js

We're getting thousands of these messages, so I was thinking of only yelling once.
To test it out: check out the `Worldview docs/Hitmap` story, compare the before and after warning messages.

Warn only once if getHitmapId is used

---

packages/regl-worldview/src/types/index.js

I am not sure this is the right approach here but it seems like optional subtype property `id` is not a thing flow accept. (https://github.com/facebook/flow/issues/3866)
We ran into problem while updating Worldview.

🧬🐛 BaseShape optional id property issue

---

docs/src/4.10.Text.mdx
docs/src/jsx/Text.js
packages/regl-worldview/src/commands/Text.js

- Allow text markers to specify background and text colors with `colors` field so that the text can be more readable. 
- Add `autoBackgroundColor` prop to `Text` in order to automatically add high-contrast background color

Allow text markers to specify background and foreground colors

---

docs/src/3.7.Glossary.mdx
docs/src/routes.js

There was some confusion around how to handle `pose`. It's unclear that the translation happens before the rotation. 
- Add a Glossary section to document different terms
- Add documentation for pose

Add documentation for pose

---

docs/src/3.1.Worldview.mdx
docs/src/3.4.MouseEvents.mdx
docs/src/jsx/utils/WorldviewCodeEditor.js
packages/regl-worldview/src/Worldview.js

The Worldview `onClick` handler is being fired even when user is panning around because currently `onClicked` is always fired after `onMouseUp`. 
Track the movement, only fire `onClick` if the mouse has moved a distance within 3 screen pixels. 
Manually test: press and pan around for long distance, the information display should not change. Will add a drag object demo later in a separate PR.

Don't trigger onClick if mouse moved beyond distance

---

docs/src/jsx/Hitmap.js
docs/src/jsx/Overlay.js

Before: clicking the Overlay will cause the objects underneath to be clicked and make the current Overlay disappear 
Fixed: click the Overlay and the Overlay doesn't change

Prevent clicking through the Overlay in Interactivity example

---

packages/@cruise-automation/button/src/index.test.js

This test didn’t even work properly, since it passed even when removing
the `delay` bit. I couldn’t quite figure out the best way to fix this
test so I just removed it. This test has caused us more trouble than
prevented bugs. It’s not sparking any joy any more.

Remove flakey test on <Button>

---

docs/src/jsx/allLiveEditors.js
docs/src/jsx/examples/Hitmap.js
docs/src/jsx/utils/WorldviewCodeEditor.js
docs/src/jsx/utils/codeSandboxStyleFix.css

As shown below, the text disappears after editing the code. We did some [perf improvement](https://github.com/cruise-automation/webviz/blob/master/packages/regl-worldview/src/commands/Text.js#L33)  by dynamically creating shared global styles for Text. However, the CodeSandbox is not persisting the style between renders.   
Fixed by adding the needed styles to CodeSandbox examples, which can be configured through `makeCodeComponent`'s options. 
Manually test that changing the code won't cause the text to disappear. 
No impact.

Fix text disappearing after code update in CodeSandbox

---

packages/regl-worldview/src/Worldview.js

Suggested by @jtbandes  [here](https://github.com/cruise-automation/webviz/pull/103/files#r267911290): if the camera if fully controlled, we shouldn't allow the any mouse interactions, because the camera should be managed by the consumer. 
Manually test
**before**: moving the mouse will cause the object to shift a little and snap back right away [demo](https://cruise-automation.github.io/webviz/worldview/#/docs/tutorial/managing-the-camera):
**after**:  moving the mouse doesn't cause any shifting when Worldview is fully controlled. 
No impact if Worldview is correctly used for `controlled` and `uncontrolled` camera state.

Skip rendering CameraListener if Worldview is fully-controlled

---

docs/src/2.3.RenderingObjects.mdx
docs/src/2.4.ManagingTheCamera.mdx
docs/src/App.js
docs/src/routes.js

For long pages such as Worldview and the tutorials, it's a little inconvenient to not be able to link to a specific section. 
This PR addresses this issue:
- Auto generate links for all h1, h2 and h3 tags in the markdown docs 
- Auto scroll to the heading when the URL path's last part is matched with the heading's text content
Manual test:
No impact.

Auto generate links for h1, h2 and h3 links in markdown

---

package-lock.json
package.json

I believe this is causing some problems with internal unit tests (`TypeError: Cannot read property 'getContext' of undefined `). We also did this internally as part of the React 16.8 upgrade.

upgrade jest-canvas-mock

---

.eslintrc.js
packages/webviz-core/src/components/Modal.js
packages/webviz-core/src/components/Panel.js
packages/webviz-core/src/components/PlaybackControls/index.js

Add eslint rule for import/external-module-folders to remove the eslint disable and keep internal and external repos linting in sync. 
CI shouldn't fail.
No impact.

Fix eslint import order for internal packages

---

docs/src/jsx/utils/Scrubber.js

The [camera](https://cruise-automation.github.io/webviz/worldview/#/docs/api/camera) page is broken. This PR fixes it.
The page should load locally. I also tested all other pages. 
No impact.

Fix camera docs page

---

packages/regl-worldview/src/camera/CameraListener.js

Recently chrome changed the behavior of wheel listeners to be passive by default.  Passive listeners cannot cancel event propagation.  When a wheel event propagates outside of the canvas it can drastically slow down the browser as the parent elements try to compute whether or not they can scroll and can sometimes result in reflows and general UI jank.  This change uses manual event listener management to add active listeners, which is inline w/ the behavior for chrome before version 73.
example of the warning:
Further reading: https://github.com/facebook/react/issues/14856
https://github.com/facebook/react/issues/6436
Use mouse wheel to change zoom on a view. Notice there are no console.warn messages about passive listeners anymore.
this is semver patch.  Bugfix only.

Make wheel listener active

---

docs/src/jsx/examples/Composition.js
docs/src/jsx/utils/Scrubber.js
packages/regl-worldview/src/commands/GLTFScene.js
packages/regl-worldview/src/commands/Lines.js
packages/regl-worldview/src/commands/Triangles.js
packages/regl-worldview/src/utils/commandUtils.js
packages/regl-worldview/src/utils/fromGeometry.js

We've encountered a few [bugs](https://github.com/cruise-automation/webviz/pull/100) where triangles' depth value was causing weird behaviors demonstrated as below: the stop sign is always behind the axes no matter where we place the camera.
https://codesandbox.io/s/qkv1793yrw 
Update existing commands to take `blend` and `depth` as prop in order to customize per draw call, e.g. 
```
<Triangles>
{[
depth: { enable: true, mask: false },
blend: { enable: false },
pose: {
position: { x: 0, y: 0, z: 0 },
orientation: { x: 0, y: 0, z: 0, w: 1 },
},
points: ...,
colors: ...,
]}
</Triangles>
```
With the change, the `blend` and `depth` props are now transparent, the consumer should see the expected behaviors when they pass in the right props.  
Also manually test that the composition example is …

 Add option to customize blend and depth

---

docs/src/4.6.Lines.mdx
docs/src/App.js
docs/src/jsx/allLiveEditors.js
docs/src/jsx/commands/LinesHitmap.js
docs/src/jsx/utils/LinesWithClickableInterior.js
docs/src/jsx/utils/WorldviewCodeEditor.js
packages/regl-worldview/src/commands/Command.js
packages/regl-worldview/src/commands/Cones.js
packages/regl-worldview/src/commands/Cubes.js
packages/regl-worldview/src/commands/Cylinders.js
packages/regl-worldview/src/commands/FilledPolygons.js
packages/regl-worldview/src/commands/Lines.js
packages/regl-worldview/src/commands/Points.js
packages/regl-worldview/src/commands/Triangles.js
packages/regl-worldview/src/utils/hitmapDefaults.js

Add hitmap support to Lines so the user can click on the lines.
A few other small changes:
- Fix the props doc for Lines 
- Add query param `disableScroll` (nice to keep the page's scroll position during development)
- Clean up some prettier disable lines
- Add a new file `LinesWithClickableInterior` for the hitmap example in order to show to click the interior of the Polygon created by connecting the lines' points. 
Add a new `LinesHitmap` example:
```
const greenLines = {id: 191, points: ...}
const redLines = {id: 200, points: ...}
// Green lines, each point has different `objectId` which will be returned after clicking
<Lines onClick={...} >{greenLines} </Lines>
// Red lines with fillColor and border
<LinesWithClickableInterior onClick={...}  enableClickableInterior showBorder …
```

 Add mouse interaction to Lines

---

docs/src/4.12.GLTFScene.mdx
docs/src/jsx/allLiveEditors.js
docs/src/jsx/commands/DuckSceneHitmap.js
packages/regl-worldview/src/commands/GLTFScene.js

Add hitmap support for `GLTFScene` so the user can interact with the 3D models. 
Add `DuckSceneHitmap.js` example:
Minor: new api added and it's backward compatible.

Add mouse interaction to GLTFScene

---

packages/regl-worldview/src/Worldview.js

[This PR](https://github.com/cruise-automation/webviz/pull/114) disabled the camera listener and `onCameraStateChange` callback if the user supplied a `cameraState` to the component.  This breaks controlled components which register an `onCameraStateChange` callback + `cameraState` and use the callback + last camera state to control the component.  
The original change was similar to removing the `onChange` callback to an `<input />` element if the `value` property is supplied....it makes controlling the component based on user input impossible, since you are never notified of a change event.
Tested storybooks locally & docs locally.  Controlled cameras respond to mouse movement as expected now.
This is a semver patch change (bugfix only).

Fix for controlled camera with state change callback.

---

.vscode/settings.json
packages/regl-worldview/src/commands/GLTFScene.js

Address Jacob's [comment](https://github.com/cruise-automation/webviz/pull/132/files#r277456567): remove redundant `drawHitmap` and always draw hitmap if `id` is present. This is helpful for preventing clicking through objects in the 3d space. (Currently Worldview doesn't automatically draw hitmap for all which may cause some overlay clicking issue. We'll discuss and address it later.)
The existing GLTF hitmap example continues to work as expected. 
No impact

Improve GLTF hitmap logic

---

.circleci/config.yml

Pushed a new version of the Docker image as cruise/webviz-ci:0.0.7;
this PR just makes it so we actually use it in CI.
Test plan: is tests.
Versioning impact: none.

Update CI to use Chrome 74

---

package.json

Our deploy script was auto-removing the file that was configured through the GH web UI.

add CNAME to gh-pages directory

---

docs/src/jsx/utils/LinesWithClickableInterior.js
docs/src/jsx/utils/WorldviewCodeEditor.js

The Mouse Interaction example for lines is broken in codesandbox due to missing the util file and lacking support for flowtypes and `<></>`.
The new codesandbox link should work: https://codesandbox.io/s/delicate-violet-ytw2o
No impact.

Fix clickable interior example for codesandbox

---

docs/public/index.html

For better embedding in Slack and other sites/tools that support [OpenGraph](http://ogp.me/).
Also removed a `<link>` to a CSS file that didn't exist.

add OpenGraph tags to landing page

---

packages/regl-worldview/src/Worldview.js

We had some incorrect logic that would cause the Worldview component
to read from the hitmap on every mouse move even if hitmapOnMouseMove
was false, as long as there was no `onMouseMove` handler. Fix it and
make the logic path a bit clearer.
Test manually with interactions on the demo page to make sure they aren't
broken.
Requires a patched version.

Fix reading hitmap on every mouse move

---

.gitignore
package.json
packages/webviz-core/package-lock.json
packages/webviz-core/package.json
webpack.config.js

Bump the lz4-wasm package with the corresponding webpack config. I also took out the old way of pulling in the wasm module (specified in the root `package.json`). 
Verified build was working, and the wasm dependency was pulled in. 
We don't distribute webviz-core as a package right?

Bump wasm-lz4

---

docs/src/4.14.Grid.mdx
docs/src/jsx/allLiveEditors.js
docs/src/jsx/commands/Grid.js
docs/src/routes.js
packages/regl-worldview/src/commands/Grid.js

Because of the changes to hitmap rendering, grid rendering broke.
Fix it by updating the shader to handle new hitmapId mapping, and
also add a doc page for grids.
Added grid doc route, manually tested
May require a 0.2.1 package for fixes.

Fix grid not rendering

---

packages/webviz-core/package-lock.json
packages/webviz-core/package.json

Looks like things got out of sync with https://github.com/cruise-automation/webviz/pull/199. I forgot to bump the package.json in the internal repo, so when things got copied over, we got the old version of wasm-lz4.

Re-bump wasm-lz4

---

docs/src/jsx/utils/codeSandboxUtils.js
package.json
packages/webviz-core/src/stories/inScreenshotTests.js
stories/inScreenshotTests.js

We need a different user agent for some proprietary integration tests.
Change to one that better matches the default chrome user agent.
Test plan: passes CI

Fix issue with screenshot test user agent

---

docs/src/2.5.AddingInteractivity.mdx
docs/src/3.2.Camera.mdx
docs/src/jsx/api/CameraState.js
docs/src/jsx/api/CameraStateControlled.js
docs/src/jsx/api/CameraStateUncontrolled.js
docs/src/jsx/commands/GLTFScene.js
docs/src/jsx/commands/GLTFSceneHitmap.js
docs/src/jsx/commands/LinesHitmap.js
docs/src/jsx/commands/LinesInstability.js
docs/src/jsx/commands/LinesWireframe.js
docs/src/jsx/commands/Points.js
docs/src/jsx/commands/SpheresInstancedColor.js
docs/src/jsx/examples/Composition.js
docs/src/jsx/examples/Hitmap.js
docs/src/jsx/tutorials/AddRemoveObstacles.js
docs/src/jsx/tutorials/FollowObject.js
docs/src/jsx/tutorials/FollowObjectOrientation.js
docs/src/jsx/tutorials/MoveCamea.js
docs/src/jsx/tutorials/StopReleaseDuck.js
docs/src/jsx/utils/CameraStateControls.js
docs/src/jsx/utils/Slider.js
packages/regl-worldview/src/Worldview.js
packages/regl-worldview/src/camera/CameraStore.js
packages/regl-worldview/src/camera/CameraStore.test.js
packages/regl-worldview/src/camera/camera.js
packages/regl-worldview/src/stories/Cubes.stories.js
packages/regl-worldview/src/stories/Worldview.stories.js
packages/regl-worldview/src/stories/cameraState.stories.js

Add `fov`, `near`, and `far` to `cameraState` so they can be customized. Also add these new properties to the interactive documentation:
Unit tests pass with no regressions; added the new properties to `CameraStore` tests. Manual inspection confirms that the properties behave as expected.
Minor update due to the backward-compatible new features.

Add FOV and frustum plane distances to cameraState

---

docs/src/jsx/utils/codeSandboxUtils.js
stories/inScreenshotTests.js

We have three copies of the same function. Unfortunately we can't
really share them since they have very different contexts and one
is inside the webviz-core package, but instead make sure they have
the same definition.
Test plan: tests pass

Unify inScreenshotTests

---

docs/src/4.1.Arrows.mdx

Fix small documentation error. `orientation` should take in a `w` field rather than `q`.
Doc change -- no need for test.
No need to update version.

Fix arrow doc

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json
packages/regl-worldview/src/commands/Grid.js
packages/regl-worldview/src/utils/getChildrenForHitmapDefaults.js

Fix two minor issues:
* Don't wrap Grid in a `React.memo` call. No other commands do this.
* Don't require "colors" in a command prop for instancing to be enabled for that command in our default `createInstancedGetChildrenForHitmap`. Instead we always populate the `colors` array if there is a `points` array. The current behavior is confusing, since many people expect instancing to be enabled even if they're using a single color, and the workaround (provide an empty color array) is a bit weird.
Automated testing/flow should be able to catch all issues here.
Release new version of Worldview that includes the changes to Lines.

Fix minor Worldview issues and release new version

---

packages/webviz-core/package-lock.json
packages/webviz-core/package.json

There was a duplicate `monaco-editor` dependency in the `webviz-core` package.json, causing that instantiation to not load the Typescript language service. I'll take out the corresponding dependency out of the private repo. 
Tested locally with docs.
None

Add monaco editor fix

---

docs/src/4.11.Triangles.mdx
packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json
packages/regl-worldview/src/WorldviewContext.js
packages/regl-worldview/src/commands/Cones.js
packages/regl-worldview/src/commands/Cubes.js
packages/regl-worldview/src/commands/Cylinders.js
packages/regl-worldview/src/commands/GLTFScene.js
packages/regl-worldview/src/commands/Points.js
packages/regl-worldview/src/commands/Spheres.js
packages/regl-worldview/src/commands/Triangles.js
packages/regl-worldview/src/stories/assertionStories/Triangles.stories.js
packages/regl-worldview/src/types/index.js

For performance reasons we sometimes want to only render triangles when clicking. Add an option to allow this. Modify the command API somewhat to enable this. Also do a small cleanup: move all of the `createInstancedGetChildrenForHitmap` calls out of the render functions of commands.
Added a story with this new behavior.
Minor package increment needed.

Add option to only render triangles in the hitmap

---

docs/src/3.4.MouseEvents.mdx
packages/regl-worldview/package.json
packages/regl-worldview/src/Worldview.js
packages/regl-worldview/src/commands/DrawPolygon/PolygonBuilder.test.js
packages/regl-worldview/src/stories/assertionStories/Worldview.stories.js
packages/regl-worldview/src/types/index.js

We want to mimic how the browser [Event.stopPropagation](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) works in Worldview, e.g. calling `event.stopPropagation()` in a click handler on a nested div would prevent any click event handlers from firing off in ancestor divs. This PR accomplishes a similar behavior for Worldview by changing the order in which global vs command level mouse handlers are fired as well as using [React's synthetic event's isPropagationStopped](https://reactjs.org/docs/events.html#overview) property.
Added two storybook tests
This probably necessitates a major/minor patch as it can be a breaking change to those who use `e.stopPropagation` in command level mouse handlers or those who expect the worldview level mouse handlers to fire off before …

A first take on stopPropagation within worldview

---

.vscode/settings.json
package-lock.json
package.json
packages/webviz-core/package-lock.json

The inconsistent style-components version is causing a few ColorPicker related screenshots to fail in #289.  This is mainly due to the ColorPicker use `ref` which is only supported in styled-components v4 ([innerRef deprecated](https://www.styled-components.com/docs/api)). Fixed by updating styled-components to v4. 
The existing screenshots should pass.

Fix ColorPicker screenshots by upgrading styled-components

---

docs/public/index.html

Tiny consistency fix, it just bugged me that for webviz.io the title was "Webviz" but for webviz.io/app it's "webviz". We use the lowercase version in the title bar so I figured I'd just use that for the main page as well. 🙃

Title capitalization

---

package.json

fixes: #321 
from a contributors standpoint, I think that this field is confusing as this repo is not using yarn workspaces. Thus, removing it would make working within this repo easier.
- install and bootstrap works as intended and symlinks are preserved
N/A

chore: remove yarn workspace key

---

package-lock.json
packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json
packages/regl-worldview/src/WorldviewContext.js
packages/regl-worldview/src/stories/assertionStories/Worldview.stories.js
packages/regl-worldview/src/stories/worldviewAssertionUtils.js
packages/regl-worldview/src/utils/queuePromise.js
packages/regl-worldview/src/utils/queuePromise.test.js
packages/regl-worldview/src/utils/signal.js
stories/assertionTestUtils.js

I'm seeing an error in our logs: "(regl) can not resize a framebuffer
which is currently in use" in the readHitmap function. Fix by debouncing
the readHitmap function because the framebuffer can only be used in
one function at a time. Also add caching to our readHitmap function: if
we haven't repainted or changed the pixel that we're looking at, we return
the previous result.
Test plan: test added for queuePromise for caching. Testing that caching
actually works (an implementation detail) seems a bit difficult right now
given our test harness.
Release plan: minor release required

Worldview: fix hitmap bug

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json

The previous release was not published with a latest build of master. We could unpublish that version and republish, but it's a bit dangerous that way (e.g. you could delete the entire package from the npm registry). @davidswinegar and I considered this the safer route.

Release regl-worldview v0.4.0

---

packages/webviz-core/src/panels/Rosout/index.js
packages/webviz-core/src/panels/Rosout/index.stories.js
packages/webviz-core/src/util/globalConstants.js

Adds `<TopicToRenderMenu>` to the RosOut panel. No version impact (backward compatible).

RosOut: add TopicToRenderMenu

---

webpack.config.js

Revisiting this old issue that I couldn't figure out a few months ago. After loading up https://webviz.io/app/?demo, I saw this error:
Turns out our worker-loader was scooping up `*.worker.js` files in node_modules, and was doing a double-require (hence the syntax error shown above).
Solution is to just exclude `node_modules` from the worker-loader. Pretty straightforward, and mimics our private webpack.config.js.
Tested with `npm run docs`, and should pass CI.
Only effects webviz-core -- no version bump needed.

Fix worker loader

---

jest/jest.config.js

Just mock out every worker-loader call in Jest, because Jest
doesn't like worker calls.

Mock all workers in jest

---

packages/webviz-core/src/stories/setup.js
stories/config.js

We'd like to be able to run custom setup code for storybook to support new features we're adding internally. For now it'll just be a no op.
Tested build and storybook locally, brought over internally repo and confirmed we can use this change to address our current issues.
No, only a test change.

Add stories setup config flow for webviz-core

---

README.md
package.json

And also only do one at a time.
This makes it so that screenshots are less likely to cause a timeout in CircleCI, and also gives us more information to debug if a screenshot hangs the system.

Make screenshot tests more verbose

---

packages/webviz-core/src/dataProviders/MemoryCacheDataProvider.js
packages/webviz-core/src/dataProviders/MemoryCacheDataProvider.test.js

While there is space left in the cache and there are no read requests currently in flight, the `MemoryCacheDataProvider` should intelligently fill up its cache.
This is currently already done for files shorter than 35 seconds long, but
- We'd rather just have one threshold (size) rather than two (size and length), and
- The technique currently used for short files ("request the whole thing") is not appropriate for files that won't fit in the cache.
The first couple of commits reorder some of the logic in the class to make the call graph simpler, replacing some mutual recursion with explicit iteration. Most of the changes are in the final commit.
A test has been added to demonstrate some new behaviour -- loading data *before* a read-request when there's enough space in the cache. Other …

MemoryCacheDataProvider prefetches more data for "large" files

---

packages/regl-worldview/src/camera/camera.js
packages/regl-worldview/src/commands/GLText.js
packages/regl-worldview/src/stories/GLText.stories.js

This PR fixes several issues for `<GLText />` when scale invariance is enabled:
Scale invariance is not working correctly when using orthographic projection (`perspective = false` in camera state) because we're using the w-component to compute the text scale. But that component is always 1 in orthographic mode. So, in that case we need a different approach. Check the comments in shaders for more information.
Rendered text's size was not matching the pixel size specified in scaleInvariantFontSize. Now it does, although the calculations are different for orthographic and perspective projections.
After some discussion with the team, we decided to ignore the scale property of individual markers when scale invariance is enabled, since that resulted in text being too big or too small. It is …

Fix scale invariance for both perspective and orthographic projections

---

packages/regl-worldview/src/commands/GLText.js
packages/regl-worldview/src/stories/GLText.stories.js

There's a bug in `<GLText />` resulting in some characters being cropped when rendering:
The problem is that we're not taking into account the small margin (named `BUFFER` in the code) for each glyph that is used when computing the SDF for the font.
This is the result after my fix:
I added a comment and a test as well 
Added a story to make sure each character is not cropped. It will help if we change the font in the future (I noticed a comment about that).
This should be a patch. No new functionality was added.

Fix glyph size when rendering text

---

packages/regl-worldview/src/commands/GLText.js
packages/regl-worldview/src/stories/GLText.stories.js

When rendering text using `<GLText />`, if two or more markers share the same position they will be displayed one on top of the other, which makes it harder to read.
The following changes avoid the overlap by rendering new markers in different lines (provided they share the same position, of course). 
Added new stories for testing this behavior in particular.
Patch

Fix overlapped markers when using GLText

---

docs/src/4.15.GLText.mdx
packages/regl-worldview/src/commands/GLText.js
packages/regl-worldview/src/stories/GLText.stories.js
packages/regl-worldview/src/utils/commandUtils.js

These changes help `<GLText />` markers to be rendered on top of other objects in the 3D world. 
Before:
After:
In order to render the text on top of other objects, depth testing needs to be disabled. 
In addition, `<GLText />` should be drawn last, which is something application developers must do themselves. I added an entry in the documentation about this.
Added three new stories to show how `<GLText />` is rendered when other objects are overlapping and whether or not scale invariance is enabled.
Patch

<GLText> Disable depth testing when scale invariance is enabled 

---

jest/jest.config.js

Inline uses of worker-loaders con include options before the bang. They
look like URL params -- question marks and equals signs etc. We want to
make a change that requires an inline option, and don't want it to break
our tests.
Existing unit tests still pass. I've also made a similar change in a different
project, and it worked... Not currently tested in this project in this PR, though
it will be when the change that depends on this is made.
None.

Jest module-mapper handles worker-loader options

---

package.json

I noticed that it was still slow, and it was because we were missing
the `--`.
Test plan: verified locally that it was broken before, and that this
fixes it.

Fix parallelism for `npm run screenshot-proprietary-ci`

---

.circleci/config.yml
Dockerfile

This is a fix for a long-winded attempt to get packages synced between
internal and open source versions. We use NPM aliasing internally, but
it doesn't seem to work in open-source - see #362, which keeps failing
the build in CI even though the build works locally. It turns out that the
version of NPM in CI (6.4.2) doesn't support package aliasing while
my local version of NPM does - support was only added in 6.9.0 
(https://npm.community/t/release-npm-6-9-0/5911).
The fix is simple: update the dockerfile version that we use to
be able to use package aliasing in CI.

Update docker CI image

---

packages/regl-worldview/src/Worldview.js
packages/regl-worldview/src/WorldviewContext.js

This is a continuation of https://github.com/cruise-automation/webviz/pull/383
As a consumer of Worldview, I was debugging performance. I found something I think is a performance anti-pattern & should be changed. I see we use a Lodash debounce on our `onDirty` which calls paint, I think this should change.
Issue # 1 - There were frames that would take so long to render that their durations would sometimes exceed a whole second (FPS dropping below 1 FPS). 
Issue # 2 - I also noticed there was a lot of work happening on the main thread, which seemed animation related, but was not running in an animation frame event, but instead was happening in a timer event. This would mean we delay painting & miss the animation frame events, which would extend painting until the next frame, delaying the …

Changing onDirty & paint to be more performance friendly

---

packages/@cruise-automation/button/package.json
packages/react-key-listener/src/index.js

Previously we'd ignore events if their target was a Button or a Select, but this breaks keyboard shortcuts once a Button has been focused. In order to keep keyboard shortcuts working all the time, we now allow events targeted at Button and Select elements.
Manually verified
It does impact the behavior so maybe minor/patch

Don't ignore keyboard events when the target is a Button or a Select

---

packages/@cruise-automation/button/package.json
packages/react-key-listener/package.json

I meant to bump the major version of `react-key-listener`, but instead bumped the version of `@cruise-automation/button`. 😅
This sets the versions straight:
* `@cruise-automation/button` on v`0.0.7`
* `react-key-listener` on v`1.0.0`

Fix versions of react-key-listener and @cruise-automation/button

---

packages/regl-worldview/src/commands/GLText.js
packages/regl-worldview/src/utils/commandUtils.js

When looking at performance tools in Webviz, I could see that the
`makeDrawText` command was being recompiled every tick. Fix this
command so that we never recompile it, saving ~8-15ms per tick (!).
Test plan: this should have no screenshot test changes.

Fix gltext recreating draw command every tick

---

.gitignore
Dockerfile-static-webviz
Dockerfile-webviz-ci
README.md
package-lock.json
package.json
webpack.config.js

Plus a Dockerfile that just installs Webviz.
There have been multiple requests for something like this, especially
from people who want to use Webviz in situations with limited internet
connectivity. See e.g. #120, #267, and #406.
I’ve also renamed the existing Dockerfile.
I’ll follow up with another PR that updates the README to explain how to
use the new Docker image once I’ve figured out how to set up automated
Docker builds.
Test plan: tested this locally. There’s some risk of this getting out of
sync since we don’t run this in CI, but hopefully with the automated
Docker build which I’ll set up later we’ll at least get some coverage on
this flow.

Add option to build just Webviz

---

packages/regl-worldview/package.json
packages/regl-worldview/src/commands/GLText.js

We have been running SDF calculations twice when the set of characters
changes -- once when the change happens (using a temporary set of
characters whose identity is always unique) and again immediately after
(using the constant-identity original `charSet`.)
This change updates the code to only do the calculation when the change
happens, and simplifies the logic a little by grouping all of the
memoization/recomputation and cache-busting decisions into one place --
the `memoizeOne` around the atlas-building function.
Test plan: I've instrumented the function during webviz startup and
verified that the SDF calculations are only done once.
Versioning impact: This is a bugfix, but it wasn't a correctness issue. Bump
the version number so people downstream can get the benefit.

Avoid running SDF calculations twice

---

README.md

Test plan: see https://hub.docker.com/r/cruise/webviz/builds or
https://hub.docker.com/repository/docker/cruise/webviz/builds — it’s
alive! Also ran the Docker command locally after deleting all my local
images, to make sure that works.

Update README now that we have Docker autobuild working

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json
packages/regl-worldview/src/commands/Triangles.js

Found when testing. In some cases, when there is an array color and
an array colors on a triangle, the rendering would fail becuase we
incorrectly use the single color instead of the array colors.

Fix worldview triangle hitmap bug

---

.flowconfig

This is a simple change in `.flowconfig` file to add support for WebAssembly files, which is required by some of the new features we are currently working on.

Update .flowconfig to support .wasm files (WebAssembly)

---

docs/src/3.1.Worldview.mdx
packages/regl-worldview/package.json
packages/regl-worldview/src/Worldview.js
packages/regl-worldview/src/camera/CameraListener.js
stories/config.js
stories/withStateReset.js

In order to allow external code to focus the Worldview element in order to get keyboard
controls working again instead of forcing the user to click the worldview element.
Test plan: Manual

Add an imperative `focus()` method to Worldview

---

docs/src/3.1.Worldview.mdx
packages/regl-worldview/src/Worldview.js

Worldview is not using the `devicePixelRatio` property to resize the `canvas`, which does not take advantage of high resolution screens (like Retina). 
In this PR, I'm adding a new property to `Worldview` named `resolutionScale`. If present, the `canvas` element will be scaled accordingly, which will let us have better control over the final image quality. The following image shows `resolutionScale` set to `devicePixelRatio`:
There should be no differences in stories.
Minor

Increase canvas resolution by using device's pixel ratio

---

docs/src/4.8.Points.mdx
packages/regl-worldview/src/commands/Points.js
packages/regl-worldview/src/stories/Points.stories.js
packages/regl-worldview/src/stories/assertionStories/Points.stories.js
packages/regl-worldview/src/types/index.js

By default, <Points /> uses the `scale` property to determine the size of all points. `gl_PointSize` expects values in pixels rather than in units in world space, though.
The changes in this commit introduce a new optional flag to use world space point sizes instead of pixels. In order to accomplish that goal, the vertex shader computes a scaled point size based on the current view transformation and render target size.
Test plan: Added new stories for `<Points />` command, using both screen and world space point sizes with unit cubes for reference.
Minor: the new flag is used to ensure backward compatibility

Use world units for point sizes

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json
packages/regl-worldview/src/Worldview.js
packages/regl-worldview/src/utils/Dimensions.js

Similar to what is coming to the rest of Webviz, but use this in the
Worldview. Replace the inefficient react-container-dimensions with
custom Dimensions.
Test plan: screenshot tests.

Replace react-container-dimensions with custom code in Dimensions

---

packages/regl-worldview/package.json
packages/regl-worldview/src/commands/GLTFScene.js

The `scene` property is optional. If it's not specified, use "the first"
scene.
In a .glb file I opened that didn't have a specified scene, there was
one key in the `scenes` object: `"0"`. In GLTF 2 `scenes` is an array, so
we might be able to get away with just `scenes[0]`, but this seems
slightly more robust.
I don't think we need to be super careful about files without scenes.
Maybe we want some controls for the scene to draw to be specified in the
command if there could be more than one, but let's not worry about that
until we come across it.
Tested by loading a file up in the worldview docs site locally. I don't have
a publicly available .glb example.

Do not require a scene in GLTF

---

docs/src/4.1.Arrows.mdx
docs/src/4.2.Cones.mdx
docs/src/4.3.Cubes.mdx
docs/src/4.4.Cylinders.mdx
docs/src/4.9.Spheres.mdx
packages/regl-worldview/src/commands/Cones.js
packages/regl-worldview/src/commands/Cubes.js
packages/regl-worldview/src/commands/Cylinders.js
packages/regl-worldview/src/commands/Spheres.js
packages/regl-worldview/src/stories/Arrows.stories.js
packages/regl-worldview/src/stories/Cones.stories.js
packages/regl-worldview/src/stories/Cubes.stories.js
packages/regl-worldview/src/stories/Cylinders.stories.js
packages/regl-worldview/src/stories/Spheres.stories.js
packages/regl-worldview/src/stories/util.js
packages/regl-worldview/src/utils/withRenderStateOverrides.js

In order to support advanced rendering techniques, geometry-based commands like `<Cubes />`, `<Cylinders />` or `<Arrows />` need to allow to set custom `depth` and `blend` states (in a similar way as `<Lines />` currently does). Those custom settings are directly forwarded to Regl during rendering. 
Memoization is used to prevent creating too many commands instances for the same params.
New screenshot tests have been added for the related commands
Minor. Changes are backward compatible.

Add support for custom render states on geometry-based commands

---

packages/regl-worldview/src/commands/Triangles.js
packages/regl-worldview/src/stories/FilledPolygons.stories.js
packages/regl-worldview/src/stories/Triangles.stories.js

This PR uses `withRenderStateOverrides` to set custom depth and blend values in both `<Triangles />` and `<FilledPolygons />`. This is required for advanced rendering modes in Webviz, life `Diff Mode`. 
New stories were created for both commands, with and without render state overrides. 
Minor. This is a bug fix and it's backward compatible.

Allow custom render states for <Triangles /> and <FilledPolygons />

---

packages/regl-worldview/src/utils/withRenderStateOverrides.js

The function `withRenderStateOverrides` does not handle memoization correctly, leading to performance issues on Worldview clients. Since `memoizedRender` is created and invoked in the same scope, the memoization does not really happens.
I'm moving the memoization so it is done outside of `renderElement`, which is the correct approach. After this change, performance is back to normal
Cover by existing screenshot tests.
Patch.

Worldview: Fix render state memoization to avoid performance issues

---

packages/regl-worldview/src/stories/Triangles.stories.js
packages/regl-worldview/src/utils/withRenderStateOverrides.js

The `<Triangles />` command has custom render states by default (depending on if we're using the same color for all points or not). But `withRenderStateOverrides` is not taking those defaults into account and it always overrides them with the Regl ones.
I'm making a small change to make sure the render states provided by commands, if any, take precedence over the Regl default ones.
I added a story that shows the correct behavior. The rest of the stories/tests should pass.
Patch. This is a bug fix.

<Worldview /> Favor render state provided by commands over the Regl ones

---

packages/regl-worldview/package.json
packages/regl-worldview/src/commands/Lines.js

Whenever we render a line we copy over the whole buffer, which is as
long as the longest line we've ever seen. This can be very inefficient
if there are a small number of very long lines and a large number of
short lines.
Test plan: No functional changes. Screenshots should stay unchanged.
Bumped minor version.

Less buffer copying in <Lines>

---

docs/src/3.1.Worldview.mdx
packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json
packages/regl-worldview/src/Worldview.js
packages/regl-worldview/src/WorldviewContext.js

Allow passing in context attributes in Worldview that will be used
when creating the context from `getContext`.

Allow adding context attributes in Worldview

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json
packages/regl-worldview/src/commands/Points.js

`useWorldSpaceSize` must be optional for `<Points />`
Covered by existing tests. Manual test too.
Patch to v0.15.0

Fix <Points /> optional world size argument

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json
packages/regl-worldview/src/Worldview.js
packages/regl-worldview/src/index.js

In this PR I'm modifying Worldview so it can use an offscreen `<canvas />` that is managed by the client application. If an offscreen canvas is used, clients must use the `<OffscreenWorldview />` component instead of `<Worldview />` one since dimensions are handled externally.
Additional changes are required to forward mouse events to rendering components, since they're now initiated in an external element. 
Handled by existing tests in Webviz. 
Minor. These changes are backward compatible.

Add support for rendering Worldview in an offscreen canvas

---

stories/config.js

We're currently working on supporting web workers in 3D Panel, which requires to send binary objects across worker boundaries. The `FinalizationRegistry` is used to release those objects when they're no longer used in main thread. But `FinalizationRegistry` is not present in the test environment.
Manually tested so far since workers are experimental.
Patch

Add fallback for FinalizationRegistry in stories

---

packages/webviz-core/package-lock.json
packages/webviz-core/package.json
packages/webviz-core/src/panels/ThreeDimensionalViz/withTransforms.js

Fix this issue where `withTransforms` seems to violate the rules of hooks: https://github.com/cruise-automation/webviz/issues/600
React is complaining that returning a function component here breaks the "rules of hooks".
I tried setting `Component.prototype = React.Component.Prototype` like the warning suggests, but it didn't seem to help.
I messed with it for a while trying to get it to work, but couldn't figure out why React is fine with this approach in `FrameCompatibilityDEPRECATED`, but doesn't like it in `withTransforms`. It might be due to the double layer of `hoistNonReactStatics`/`React.forwardRef` in both `FrameCompatibilityDEPRECATED` and `withTransforms`? I'm not entirely sure, but switching it back to a class component fixes the problem in the short-term.

Fix withTransforms() breaks the rules of hooks

---

packages/regl-worldview/package.json
packages/regl-worldview/src/commands/GLText.js

This is half-reasonable, half-hack:
* Preferring `OffscreenCanvas`, and detecting it at runtime is
reasonable.
* Hacking `document` for TinySDF is a bit crazy. I've raised an issue
upstream, hopefully this won't live long.
Upstream issue: https://github.com/mapbox/tiny-sdf/issues/35
Test plan: Linked against a local webviz and opened a bag containing a
strange character with the worker flag on.

Make GLText work in workers

---

webpack.config.js

Upgrade the Buffer package to avoid using the default one provided by Webpack. This is a requirement to support `SharedArrayBuffers` in a later commit.
Test plan: covered by existing tests. Also tested manually.

Use latest Buffer package to support shared arrays

---

.circleci/config.yml
Dockerfile-static-webviz
package-lock.json
package.json
packages/regl-worldview/src/utils/queuePromise.test.js
packages/webviz-core/package-lock.json
packages/webviz-core/shared/recordVideo.test.js
packages/webviz-core/src/dataProviders/MemoryCacheDataProvider.test.js
packages/webviz-core/src/players/RandomAccessPlayer.test.js
packages/webviz-core/src/util/debouncePromise.test.js

The previous build updated the dockerfile, but didn't switch the build over to use Node 12.
Now, we'll use `cruise/webviz-ci:0.0.13` to run the build. `cruise/webviz-ci:0.0.13` is the first published Node 12 docker image.
I had to mess with the tests a bit to get them to pass. It seems like the way Node 12's async `.finally` changed timing. Nothing too crazy – mostly adding a few extra delays/awaits. I think the weirdest change is in `MemoryCacheDataProvider.test.js` where I had to change a 10 to an 11. I don't see anything async there, so that one is bit mysterious. Please let me know if you find it concerning!
Test plan: All tests consistently pass using Node 12.22.0

Run the CircleCI Build using Node 12

---

packages/webviz-core/package-lock.json

The package-lock file was referencing `artifactory.robot.car` which isn't available to open-source users. Replace them with npm registry entries.
I'll open a new PR to add a lint rule so this doesn't happen again, but I wanted to get this fix out asap.

Remove references to artifactory.robot.car from package-lock.json

---

babel.config.js
package-lock.json
package.json
packages/webviz-core/shared/recordVideo.js

We already enabled this in the closed-source repo, but let's add it here as well.
This allows all code to import using paths like `import X from "webviz-core/any/path"`.
This allows script files like `record-local-bag-video.js` to use absolute import paths as well. I realized we needed this when the close-source repo started erroring when running the `test_with_open_source` due to this error: `Error: Cannot find module 'webviz-core/src/util/globalConstants'`. This was because this repo has relied on some import paths being relative, but this should resolve it going forward.

Allow absolute import paths everywhere

---

flow-typed/npm/react-router-dom_v5.x.x.js

We are using v5.3.0 of `react-router-dom`, so this updates the flow types to match. This is required before we can start to use the new `useHistory` hook.

Update the flow-typed definition for react-router-dom to v5

---

packages/@cruise-automation/button/package.json
packages/@cruise-automation/button/src/index.js
packages/webviz-core/src/components/Button.js

There seems to be no easy way to select buttons for clicking in tests. Added `data-test` tag to `<button>` so that it can be tested. Note: The prop is `dataTest`, but becomes `data-test` on the button to match existing patterns.
Tested manually to verify that the tag comes through.
This shouldn't affect versions.

Add dataTest to button props for testing

---

packages/regl-worldview/package-lock.json
packages/regl-worldview/package.json
packages/regl-worldview/src/utils/fromGeometry.js

Vertex offset is currently applied after the pose, but offset is in local space instead of world space.
This lead to a bug where marker orientations end up being ignored in some cases.
Notice how spheres are not in the correct final position for the object to the right of the screen. Orientation is not applied in this case (spheres have the same orientation as in the object to the left).
Now spheres are in the correct position and orientation.
All existing tests must pass
This is a bug fix, so it should be a patch.

Add vertex offset before applying geometry's pose

---

integration-tests/install-ffmpeg-in-docker.sh

Otherwise CI fails with the error:
```
[2022-03-10T19:29:48Z]   The following signatures were invalid: EXPKEYSIG 8B48AD6246925553 Debian Archive Automatic Signing Key (7.0/wheezy) <ftpmaster@debian.org> REVKEYSIG 7638D0442B90D010 Debian Archive Automatic Signing Key (8/jessie) <ftpmaster@debian.org>
--
  | Reading package lists... Done
  | [2022-03-10T19:29:49Z] W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/google-chrome.list:3 and /etc/apt/sources.list.d/google.list:1
  | [2022-03-10T19:29:49Z] W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/google-chrome.list:3 and /etc/apt/sources.list.d/google.list:1
  | [2022-03-10T19:29:49Z] W: GPG error: http://archive.debian.org/debian …
```

Fix repository update
